(() => {
  const ADMIN_SESSION='verv_admin_session_v1';
  function adminGate(){
    const gate=document.getElementById('adminGate'); if(!gate)return true;
    const allowed=String(window.VERV_CONFIG?.ADMIN_EMAIL||'').toLowerCase();
    const session=localStorage.getItem(ADMIN_SESSION)||'';
    if(session && session.toLowerCase()===allowed){gate.remove();document.body.classList.add('admin-authenticated');return true;}
    document.body.classList.add('admin-locked');
    const note=document.getElementById('adminGateNote'), btn=document.getElementById('adminGoogle');
    const load=()=>{if(!window.google?.accounts?.id){if(note)note.textContent='Google sign-in needs a Google OAuth Client ID in config.js before real owner authentication can run.';return;}
      window.google.accounts.id.initialize({client_id:window.VERV_CONFIG.GOOGLE_CLIENT_ID,callback:r=>{
        try{const part=r.credential.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');const d=JSON.parse(decodeURIComponent(atob(part).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join('')));
          if(String(d.email||'').toLowerCase()!==allowed){if(note)note.textContent='This Google account is not the VERV owner account.';return;}
          localStorage.setItem(ADMIN_SESSION,d.email);gate.remove();document.body.classList.remove('admin-locked');document.getElementById('adminIdentity').textContent=d.email;
        }catch{if(note)note.textContent='Could not verify the Google account. Please try again.';}
      }});
      window.google.accounts.id.prompt();
    };
    btn?.addEventListener('click',()=>{if(!window.VERV_CONFIG?.GOOGLE_CLIENT_ID){if(note)note.textContent='Add the Google OAuth Web Client ID to config.js. The allowed owner email is '+allowed+'.';return;} if(window.google?.accounts?.id)load();else{const sc=document.createElement('script');sc.src='https://accounts.google.com/gsi/client';sc.async=true;sc.onload=load;document.head.appendChild(sc);}});
    document.getElementById('adminLocal')?.addEventListener('click',()=>{const entered=prompt('Enter the VERV owner email for local preview:');if(String(entered||'').toLowerCase()===allowed){localStorage.setItem(ADMIN_SESSION,allowed);gate.remove();document.body.classList.remove('admin-locked');document.getElementById('adminIdentity').textContent=allowed;}else if(note)note.textContent='Access denied.';});
    return false;
  }
  adminGate();
  const PKEY='verv_admin_products_v1', CKEY='verv_admin_categories_v1', SKEY='verv_admin_settings_v1';
  const get=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}};
  const products=()=>get(PKEY,[]); const categories=()=>get(CKEY,[]);
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const builtCats=[{id:'tshirts',name:'T-Shirts',productCategory:'Tee'},{id:'hoodies',name:'Hoodies',productCategory:'Hoodie'},{id:'pants',name:'Pants',productCategory:'Pants',map:['Pants','Sweatpants','Cargo']},{id:'jackets',name:'Jackets',productCategory:'Jacket'},{id:'crewnecks',name:'Crewnecks',productCategory:'Crewneck'}];
  const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
  const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const readFile=file=>new Promise((res,rej)=>{
    if(!file)return res('');
    const r=new FileReader();
    r.onload=()=>{
      const src=r.result;
      const img=new Image();
      img.onload=()=>{
        const max=1200, scale=Math.min(1,max/Math.max(img.width,img.height));
        const w=Math.max(1,Math.round(img.width*scale)), h=Math.max(1,Math.round(img.height*scale));
        const canvas=document.createElement('canvas'); canvas.width=w; canvas.height=h;
        const ctx=canvas.getContext('2d'); ctx.drawImage(img,0,0,w,h);
        const out=canvas.toDataURL('image/webp',0.78);
        res(out.length < src.length ? out : src);
      };
      img.onerror=()=>res(src); img.src=src;
    };
    r.onerror=rej; r.readAsDataURL(file);
  });
  const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  let removedProductImages=[];
  function allProducts(){const base=window.VERV_PRODUCTS||[]; const locals=products();const map=new Map(base.map(p=>[p.id,p]));locals.forEach(p=>map.set(p.id,p));return [...map.values()].filter(p=>p.deleted!==true);}
  function refreshStats(){
    $('#statProducts').textContent=allProducts().length; $('#statCategories').textContent=builtCats.length+categories().length; $('#statChanges').textContent=products().length+categories().length;
  }
  function categoryOptions(selected){const opts=[...builtCats,...categories().map(c=>({id:c.id,name:c.name,productCategory:c.name}))];return opts.map(c=>`<option value="${esc(c.productCategory)}" ${c.productCategory===selected?'selected':''}>${esc(c.name)}</option>`).join('');}
  function renderProducts(){const list=$('#productsList');if(!list)return;const q=($('#productSearch')?.value||'').trim().toLowerCase();const filter=$('#productFilter')?.value||'ALL';const ps=allProducts().filter(p=>{const hay=[p.name,p.slug,p.sku,p.category,p.collection,p.shortDescription].join(' ').toLowerCase();const status=p.status||((p.available===false)?'soldout':'available');return (!q||hay.includes(q))&&(filter==='ALL'||status===filter)});if(!ps.length){list.innerHTML='<div class="empty">NO PRODUCTS MATCH THIS VIEW.</div>';return}list.innerHTML=ps.map(p=>`<article class="catalog-card"><div class="catalog-card-media"><img src="${esc(p.images?.[0]||'')}" alt="${esc(p.name)}"></div><div class="catalog-card-body"><div><small>${esc(p.category)}${p.badge?` · ${esc(p.badge)}`:''}</small><h3>${esc(p.name)}</h3><p>${esc(p.shortDescription||'')}</p></div><div class="card-meta"><span class="card-price">${esc(p.price)} EGP</span><div class="card-actions"><button class="tiny" data-edit-product="${esc(p.id)}">EDIT</button><button class="tiny" data-duplicate-product="${esc(p.id)}">DUPLICATE</button><button class="tiny delete" data-delete-product="${esc(p.id)}">DELETE</button></div></div></div></article>`).join('');
    list.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.editProduct));list.querySelectorAll('[data-duplicate-product]').forEach(b=>b.onclick=()=>duplicateProduct(b.dataset.duplicateProduct));list.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this product from the catalog?'))return;window.VERV_CATALOG.deleteProduct(b.dataset.deleteProduct)});
  }
  function duplicateProduct(id){const src=allProducts().find(x=>x.id===id);if(!src)return;const copy=JSON.parse(JSON.stringify(src));copy.id=`p-${Date.now()}`;copy.slug=`${slugify(copy.name)}-copy`;copy.name=`${copy.name} — COPY`;copy.sku=copy.sku?`${copy.sku}-COPY`:'';copy.status='draft';copy.available=false;copy.featured=false;window.VERV_CATALOG.saveProduct(copy)}
  function renderCategories(){const list=$('#categoriesList'), cs=categories();if(!cs.length){list.innerHTML='<div class="empty">NO CUSTOM CATEGORIES YET. THE BUILT-IN CATEGORIES ARE READY.</div>';return}list.innerHTML=cs.map(c=>`<article class="catalog-card"><div class="catalog-card-media"><img src="${esc(c.image||'')}" alt="${esc(c.name)}"></div><div class="catalog-card-body"><div><small>CUSTOM CATEGORY</small><h3>${esc(c.name)}</h3><p>${esc(c.description||'')}</p></div><div class="card-meta"><span class="card-price">${esc(c.subtitle||'')}</span><div class="card-actions"><button class="tiny" data-edit-category="${esc(c.id)}">EDIT</button><button class="tiny delete" data-delete-category="${esc(c.id)}">DELETE</button></div></div></div></article>`).join('');list.querySelectorAll('[data-edit-category]').forEach(b=>openCategory.bind(null,b.dataset.editCategory) && (b.onclick=()=>openCategory(b.dataset.editCategory)));list.querySelectorAll('[data-delete-category]').forEach(b=>b.onclick=()=>{if(confirm('Delete this category?'))window.VERV_CATALOG.deleteCategory(b.dataset.deleteCategory)});
  }
  function openModal(id){$(id).classList.add('open');document.body.style.overflow='hidden'}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''}
  function renderImagePreview(p, uploads=[]){const current=(p?.images||[]).filter(src=>!removedProductImages.includes(src));const all=[...current,...uploads.filter(Boolean)];$('#pImagePreview').innerHTML=all.map((src,i)=>`<div class="image-preview-item"><img src="${esc(src)}" alt="product image ${i+1}"><button type="button" class="tiny delete image-remove" data-remove-image="${encodeURIComponent(src)}">REMOVE</button></div>`).join('');$('#pImagePreview').querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{const src=decodeURIComponent(b.dataset.removeImage);if(!removedProductImages.includes(src))removedProductImages.push(src);renderImagePreview(p,uploads);});}
  function openProduct(id){const p=allProducts().find(x=>x.id===id);removedProductImages=[];$('#productModalTitle').textContent=p?'EDIT PRODUCT':'ADD PRODUCT';$('#pId').value=p?.id||'';$('#pName').value=p?.name||'';$('#pSlug').value=p?.slug||'';$('#pCategory').innerHTML=categoryOptions(p?.category||'');$('#pPrice').value=p?.price??'';$('#pSku').value=p?.sku||'';$('#pStock').value=p?.stock??'';$('#pCollection').value=p?.collection||'';$('#pAudience').value=p?.audience||'Unisex';$('#pAgeGroup').value=p?.ageGroup||'';$('#pShort').value=p?.shortDescription||'';$('#pBadge').value=p?.badge||'';$('#pDescription').value=p?.description||'';$('#pStory').value=p?.details?.story||'';$('#pMeasurements').value=p?.details?.measurements||'';$('#pColors').value=(p?.colors||[]).join(', ');$('#pSizes').value=(p?.sizes||[]).join(', ');$('#pTags').value=(p?.tags||[]).join(', ');$('#pFabric').value=p?.details?.fabric||'';$('#pFit').value=p?.details?.fit||'';$('#pCare').value=p?.details?.care||'';$('#pOrigin').value=p?.details?.origin||'';$('#pComparePrice').value=p?.comparePrice??'';$('#pStatus').value=p?.status||((p?.available===false)?'soldout':'available');$('#pSpecials').checked=p?.specialRequests!==false;$('#pFeatured').checked=!!p?.featured;$('#pWholesale').checked=p?.wholesale!==false;$('#pReplaceImages').checked=false;const tiers=p?.wholesaleTiers||[];['tier1','tier2','tier3','tier4'].forEach((id,i)=>$('#'+id).value=tiers[i]?.price??'');$('#pImage').value='';renderImagePreview(p);openModal('#productModal');}
  function openCategory(id){const c=categories().find(x=>x.id===id);$('#cId').value=c?.id||'';$('#cName').value=c?.name||'';$('#cSubtitle').value=c?.subtitle||'';$('#cDescription').value=c?.description||'';$('#cImage').value='';$('#cImagePreview').innerHTML=c?.image?`<img src="${esc(c.image)}" alt="current image">`:'';openModal('#categoryModal');}
  function orderDate(iso){try{return new Date(iso).toLocaleString('en-EG',{dateStyle:'medium',timeStyle:'short'})}catch{return iso||'—'}}
  function orderTotal(o){return `${Number(o.total||0).toLocaleString()} ${window.VERV_CONFIG?.CURRENCY||'EGP'}`}
  function renderOrders(){
    const list=$('#ordersList'); if(!list||!window.VERV_ORDERS)return;
    const all=window.VERV_ORDERS.all();
    const filter=$('#orderFilter')?.value||'ALL', query=($('#orderSearch')?.value||'').trim().toLowerCase();
    const filtered=all.filter(o=>{const hay=[o.id,o.customerName,o.customerPhone,o.customerEmail,o.customerAddress,o.customerGovernorate,o.type,...(o.items||[]).map(i=>i.name)].join(' ').toLowerCase();return (filter==='ALL'||o.status===filter)&&(!query||hay.includes(query))});
    const counts=['NEW','CONFIRMED','PREPARING','COMPLETED','CANCELLED'].map(st=>({st,n:all.filter(o=>o.status===st).length}));
    $('#navOrderCount').textContent=all.filter(o=>o.status==='NEW').length||'';
    $('#orderStats').innerHTML=counts.map(x=>`<div class="order-stat"><small>${x.st}</small><strong>${x.n}</strong></div>`).join('');
    if(!filtered.length){list.innerHTML='<div class="empty">NO ORDERS MATCH THIS VIEW.</div>';return}
    list.innerHTML=filtered.map(o=>{const itemSummary=(o.items||[]).map(i=>`${esc(i.name)} × ${i.quantity} <span>${esc(i.color||'—')} / ${esc(i.size||'—')}</span>`).join('');return `<article class="order-card" data-order-id="${esc(o.id)}"><div class="order-card-top"><div><small>${esc(o.id)}</small><h3>${esc(o.customerName||'WHATSAPP CUSTOMER')}</h3><p>${esc(o.customerEmail||'No email')} · ${esc(o.customerPhone||'No phone')}</p><p>${esc(o.customerAddress||'Address not supplied')}${o.customerGovernorate?' · '+esc(o.customerGovernorate):''}</p><p>${esc(orderDate(o.createdAt))} · ${esc(o.type||'RETAIL')}</p></div><span class="status status-${esc((o.status||'NEW').toLowerCase())}">${esc(o.status||'NEW')}</span></div><div class="order-items">${itemSummary||'No item details'}</div><div class="order-card-bottom"><strong>${orderTotal(o)}</strong><div><button class="tiny" data-edit-order="${esc(o.id)}">VIEW / EDIT</button><button class="tiny delete" data-delete-order="${esc(o.id)}">DELETE</button></div></div></article>`}).join('');
    list.querySelectorAll('[data-edit-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.editOrder));
    list.querySelectorAll('[data-delete-order]').forEach(b=>b.onclick=()=>{if(confirm('Delete this order?')){window.VERV_ORDERS.remove(b.dataset.deleteOrder);renderOrders()}});
  }
  function openOrder(id){
    const o=window.VERV_ORDERS?.all().find(x=>x.id===id); if(!o)return;
    $('#oId').value=o.id;$('#oIdDisplay').value=o.id;$('#oCustomer').value=o.customerName||'';$('#oPhone').value=o.customerPhone||'';$('#oEmail').value=o.customerEmail||'';$('#oAddress').value=o.customerAddress||'';$('#oGovernorate').value=o.customerGovernorate||'';$('#oDeliveryNote').value=o.deliveryNote||'';$('#oStatus').value=o.status||'NEW';$('#oNotes').value=o.notes||'';
    $('#oItems').innerHTML=(o.items||[]).map(i=>`<div class="order-item-detail"><div><b>${esc(i.name)}</b><span>${esc(i.color||'—')} / ${esc(i.size||'—')} · ×${i.quantity}</span>${(i.specials||[]).length?`<small>${i.specials.map(x=>esc(`${x.label||x.key}${x.value?': '+x.value:''}`)).join(' · ')}</small>`:''}</div><strong>${Number(i.price||0)*Number(i.quantity||1)} EGP</strong></div>`).join('')+`<div class="order-total-detail"><span>TOTAL</span><b>${orderTotal(o)}</b></div>`;
    openModal('#orderModal');
  }
  $('#orderForm').onsubmit=e=>{e.preventDefault();window.VERV_ORDERS.update($('#oId').value,{customerName:$('#oCustomer').value.trim(),customerPhone:$('#oPhone').value.trim(),customerEmail:$('#oEmail').value.trim(),customerAddress:$('#oAddress').value.trim(),customerGovernorate:$('#oGovernorate').value.trim(),deliveryNote:$('#oDeliveryNote').value.trim(),status:$('#oStatus').value,notes:$('#oNotes').value.trim()});$('#orderMsg').textContent='ORDER SAVED.';renderOrders();setTimeout(()=>closeModals(),350)};
  $('#orderSearch')?.addEventListener('input',renderOrders); $('#orderFilter')?.addEventListener('change',renderOrders);
  $('#clearOrders')?.addEventListener('click',()=>{if(confirm('Delete every locally stored order? This cannot be undone.')){window.VERV_ORDERS.clear();renderOrders()}});

  function renderCustomers(){const list=$('#customersList');if(!list)return;const customers=(()=>{try{return JSON.parse(localStorage.getItem('verv_customers_v1')||'[]')}catch{return[]}})();$('#navCustomerCount').textContent=customers.length||'';if(!customers.length){list.innerHTML='<div class="empty">NO CUSTOMER PROFILES SAVED IN THIS BROWSER YET.</div>';return}list.innerHTML=customers.map(c=>`<article class="catalog-card customer-card"><div class="catalog-card-body"><div><small>${esc(c.authProvider==='google'?'GOOGLE ACCOUNT':'LOCAL PROFILE')}</small><h3>${esc(c.name||'VERV CUSTOMER')}</h3><p>${esc(c.email||'No email')}</p><p>${esc(c.gender||'Gender not set')} · ${esc(c.age||'Age not set')} · ${esc(c.governorate||'Governorate not set')}</p><p>${esc(c.phone||'')} ${c.address?'· '+esc(c.address):''}</p></div><div class="card-meta"><span class="card-price">${esc(c.createdAt?orderDate(c.createdAt):'PROFILE')}</span><div class="card-actions"><a class="tiny" href="mailto:${encodeURIComponent(c.email||'')}">EMAIL CUSTOMER</a></div></div></div></article>`).join('')}
  $('#refreshCustomers')?.addEventListener('click',renderCustomers);
  $$('.side-btn[data-tab]').forEach(b=>b.onclick=()=>{$$('.side-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-panel').forEach(x=>x.classList.remove('active'));$('#tab-'+b.dataset.tab).classList.add('active');renderProducts();renderCategories();refreshStats();if(b.dataset.tab==='orders')renderOrders();if(b.dataset.tab==='customers')renderCustomers();});
  $$('[data-open-product]').forEach(b=>b.onclick=()=>openProduct());$$('[data-open-category]').forEach(b=>b.onclick=()=>openCategory());$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
  $('#pName').addEventListener('input',()=>{if(!$('#pId').value)$('#pSlug').value=slugify($('#pName').value)});
  $('#pImage').addEventListener('change',async e=>{const files=[...e.target.files];const imgs=await Promise.all(files.map(readFile));const existing=allProducts().find(p=>p.id===$('#pId').value);renderImagePreview(existing,imgs);});
  $('#cImage').addEventListener('change',async e=>{const s=await readFile(e.target.files[0]);$('#cImagePreview').innerHTML=s?`<img src="${s}" alt="preview">`:''});
  $('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#pId').value||`p-${Date.now()}`, existing=allProducts().find(p=>p.id===id);const uploads=await Promise.all([...$('#pImage').files].map(readFile));const baseImages=$('#pReplaceImages').checked?[]:(existing?.images||[]).filter(src=>!removedProductImages.includes(src));const images=[...baseImages,...uploads.filter(Boolean)].filter((v,i,a)=>a.indexOf(v)===i);if(!images.length){$('#productMsg').textContent='Please add at least one product image.';return}const status=$('#pStatus').value;const p={...existing,id,name:$('#pName').value.trim(),slug:slugify($('#pSlug').value||$('#pName').value),sku:$('#pSku').value.trim(),stock:$('#pStock').value===''?null:Number($('#pStock').value),collection:$('#pCollection').value.trim(),audience:$('#pAudience').value,ageGroup:$('#pAgeGroup').value.trim(),price:Number($('#pPrice').value||0),comparePrice:$('#pComparePrice').value===''?null:Number($('#pComparePrice').value),status,badge:$('#pBadge').value.trim(),category:$('#pCategory').value,shortDescription:$('#pShort').value.trim(),description:$('#pDescription').value.trim(),tags:$('#pTags').value.split(',').map(x=>x.trim()).filter(Boolean),colors:$('#pColors').value.split(',').map(x=>x.trim()).filter(Boolean),sizes:$('#pSizes').value.split(',').map(x=>x.trim()).filter(Boolean),images,details:{...(existing?.details||{}),fabric:$('#pFabric').value.trim(),fit:$('#pFit').value.trim(),care:$('#pCare').value.trim(),origin:$('#pOrigin').value.trim(),story:$('#pStory').value.trim(),measurements:$('#pMeasurements').value.trim()},specialRequests:$('#pSpecials').checked,featured:$('#pFeatured').checked,available:status==='available',wholesale:$('#pWholesale').checked,wholesaleTiers:[$('#tier1').value,$('#tier2').value,$('#tier3').value,$('#tier4').value].map((x,i)=>x?({min:[30,50,70,100][i],price:Number(x)}):null).filter(Boolean)};try{window.VERV_CATALOG.saveProduct(p)}catch(err){$('#productMsg').textContent='Could not save this product. Your browser storage may be full. Try smaller images or remove old catalog data.';console.error(err)}};
  $('#categoryForm').onsubmit=async e=>{e.preventDefault();const id=$('#cId').value||`cat-${Date.now()}`, existing=categories().find(c=>c.id===id), image=await readFile($('#cImage').files[0])||existing?.image||'';if(!image){$('#categoryMsg').textContent='Please upload a category image.';return}try{window.VERV_CATALOG.saveCategory({id,name:$('#cName').value.trim(),subtitle:$('#cSubtitle').value.trim(),description:$('#cDescription').value.trim(),image})}catch(err){$('#categoryMsg').textContent='Could not save this category. Your browser storage may be full. Try a smaller image.';console.error(err)}};
  const settings=get(SKEY,{});$('#setWhatsapp').value=settings.whatsapp||window.VERV_CONFIG.WHATSAPP_NUMBER;$('#setName').value=settings.name??window.VERV_CONFIG.SPECIAL_REQUESTS.name.price;$('#setText').value=settings.text??window.VERV_CONFIG.SPECIAL_REQUESTS.text.price;$('#setLogo').value=settings.logo??window.VERV_CONFIG.SPECIAL_REQUESTS.logo.price;
  $('#settingsForm').onsubmit=e=>{e.preventDefault();save(SKEY,{whatsapp:$('#setWhatsapp').value.replace(/\D/g,''),name:Number($('#setName').value),text:Number($('#setText').value),logo:Number($('#setLogo').value)});$('#settingsMsg').textContent='SAVED — refresh the storefront to use the new settings.'};
  $('#productSearch')?.addEventListener('input',renderProducts);$('#productFilter')?.addEventListener('change',renderProducts);
  $('#exportCatalog')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(window.VERV_CATALOG.exportData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`verv-catalog-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
  $('#importCatalogBtn')?.addEventListener('click',()=>$('#importCatalog')?.click());$('#importCatalog')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(confirm('Restore this backup? Current local catalog data will be replaced.'))window.VERV_CATALOG.importData(data);}catch{alert('This backup file is not valid JSON.');}e.target.value='';});
  $('#adminLogout')?.addEventListener('click',()=>{localStorage.removeItem(ADMIN_SESSION);location.reload();});
  $('#resetCatalog').onclick=()=>{if(confirm('This clears every local product/category change. Continue?')){window.VERV_CATALOG.clearAll()}};
  const adminIdentity=document.getElementById('adminIdentity');if(adminIdentity)adminIdentity.textContent=window.VERV_CONFIG?.ADMIN_EMAIL||'OWNER';renderProducts();renderCategories();refreshStats();renderOrders();renderCustomers();
})();
